# Supported languages mapping for AI Video Dubber
LANGUAGES = {
    "English": {"translator": "en", "tts_prefix": "en-"},
    "Spanish": {"translator": "es", "tts_prefix": "es-"},
    "French": {"translator": "fr", "tts_prefix": "fr-"},
    "German": {"translator": "de", "tts_prefix": "de-"},
    "Italian": {"translator": "it", "tts_prefix": "it-"},
    "Portuguese": {"translator": "pt", "tts_prefix": "pt-"},
    "Chinese (Simplified)": {"translator": "zh-CN", "tts_prefix": "zh-CN-"},
    "Chinese (Traditional)": {"translator": "zh-TW", "tts_prefix": "zh-TW-"},
    "Japanese": {"translator": "ja", "tts_prefix": "ja-"},
    "Korean": {"translator": "ko", "tts_prefix": "ko-"},
    "Russian": {"translator": "ru", "tts_prefix": "ru-"},
    "Arabic": {"translator": "ar", "tts_prefix": "ar-"},
    "Hindi": {"translator": "hi", "tts_prefix": "hi-"},
    "Turkish": {"translator": "tr", "tts_prefix": "tr-"},
    "Vietnamese": {"translator": "vi", "tts_prefix": "vi-"},
    "Thai": {"translator": "th", "tts_prefix": "th-"},
    "Dutch": {"translator": "nl", "tts_prefix": "nl-"},
    "Polish": {"translator": "pl", "tts_prefix": "pl-"},
    "Ukrainian": {"translator": "uk", "tts_prefix": "uk-"},
    "Indonesian": {"translator": "id", "tts_prefix": "id-"},
    "Khmer": {"translator": "km", "tts_prefix": "km-"},
}
